# Docker compose to run local fast API and a Postgres database

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

    volumes:
      - database_data:/var/lib/postgresql/data

  user:
    build:
      context: .
      dockerfile: ./user/Dockerfile
    command: bash -c "uvicorn user.main:app --host 0.0.0.0 --port 8080 --reload"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

  product:
    build:
      context: .
      dockerfile: ./product/Dockerfile
    command: bash -c "uvicorn product.main:app --host 0.0.0.0 --port 8081 --reload"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8081:8081"
  order:
    build:
      context: .
      dockerfile: ./order/Dockerfile
    command: bash -c "uvicorn order.main:app --host 0.0.0.0 --port 8081 --reload"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8082:8082"

volumes:
  database_data:
